#Filtering

In [ ]:
import pandas as pd

In [ ]:
bios = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/master/data/bios.csv')

In [ ]:
bios

In [ ]:
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

#### To filter all the athletes above 220cm hieght

In [ ]:
bios.loc[bios['height_cm']>220]    #providing a condition to loc function

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5673,5696,Gunther Behnke,1963-01-19,Leverkusen,Nordrhein-Westfalen,GER,Germany,221.0,114.0,NaN
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6978,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN
89075,89787,Roberto Dueñas,1975-11-01,Madrid,Madrid,ESP,Spain,221.0,137.0,NaN
120266,122147,Zhang Zhaoxu,1987-11-18,Binzhou,Shandong,CHN,People's Republic of China,221.0,110.0,NaN

In [ ]:
bios.loc[bios['height_cm']>220, ['name', 'height_cm']]    #outputing only the required columns

                   name  height_cm
5673     Gunther Behnke      221.0
5781     Tommy Burleson      223.0
6978    Arvydas Sabonis      223.0
89070          Yao Ming      226.0
89075    Roberto Dueñas      221.0
120266     Zhang Zhaoxu      221.0

#### This is filtering based on a condition

### A simpler way to do this

In [ ]:
bios[bios['height_cm']>220][['name','height_cm']]

                   name  height_cm
5673     Gunther Behnke      221.0
5781     Tommy Burleson      223.0
6978    Arvydas Sabonis      223.0
89070          Yao Ming      226.0
89075    Roberto Dueñas      221.0
120266     Zhang Zhaoxu      221.0

#### To apply multiple conditions, we use parenthesis and and, or operators

In [ ]:
bios[(bios['height_cm']>215) & (bios['born_country']=='USA')][['name','height_cm','born_country']]
#this gives the data of atheletes whose height is greater than 215cm and born country is USA

                    name  height_cm born_country
5781      Tommy Burleson      223.0          USA
6722    Shaquille O'Neal      216.0          USA
6937      David Robinson      216.0          USA
123850    Tyson Chandler      216.0          USA

### String methods

In [ ]:
bios[bios['name'].str.contains("Krishna")]      #to filter by strings
#here we can provide additional attribute 'case' which can be true or false to change it case sensitive or not
#another attr that can be used is na = False, which removes the na values

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
283,284,Ramesh Krishnan,1961-06-05,Chennai (Madras),Tamil Nadu,IND,India,170.0,63.0,NaN
19092,19226,Krishnamurty Perumal,1947-09-26,Chennai (Madras),Tamil Nadu,IND,India,174.0,78.0,NaN
19268,19404,Krishnan Kumar Aggarwal,1939-01-25,NaN,NaN,NaN,Kenya,167.0,55.0,NaN
25621,25813,Krishna Kittu,1932-01-01,NaN,NaN,NaN,India,NaN,NaN,1981-11-06
25630,25822,Krishna Pal,1934-01-01,NaN,NaN,NaN,India,NaN,NaN,2009-10-14
64095,64576,Krishna Stanton,1966-05-18,Leeton,New South Wales,AUS,Australia,172.0,55.0,NaN
72812,73366,Tambusamy Krishnan,1944-07-08,Penang,Pulau Pinang,MAS,Malaysia,180.0,67.0,2023-12-20
73361,73926,Krishna Bahadur Basnet,1959-02-17,NaN,NaN,NaN,Nepal,168.0,58.0,NaN
86335,87023,Rajeev Bala Krishnan,1971-03-31,NaN,NaN,NaN,India,NaN,NaN,NaN
90995,91721,Krishnamurthy Gobinathan,1978-01-13,NaN,NaN,NaN,Malaysia,178.0,71.0,NaN
101614,102528,V. Krishnasamy,1948-01-13,Penang,Pulau Pinang,MAS,Malaysia,NaN,NaN,2020-08-02
113134,114424,Krishna Poonia,1977-05-05,Gagarwas,Rajasthan,IND,India,182.0,80.0,NaN
131006,133761,Roy Krishna,1987-08-30,Labasa,Macuata,FIJ,Fiji,170.0,70.0,NaN
131610,134421,Ganapathi Krishnan,1989-06-29,NaN,NaN,NaN,India,NaN,NaN,NaN

In [ ]:
bios[bios['name'].str.contains("Krishna | Rama")]   #regex syntax used for OR

##### Find athletes born in a city staring with a vowel

In [ ]:
# using r before the condition is a regular expression (regex syntax)
vowel_cities = bios[bios['born_city'].str.contains(r"^[aeiouAEIOU].*", na=False)]
vowel_cities
# to turn regex off, we can pass an attr regex=False, which will turn off the regex

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN
10,11,"Élie, Comte de Lastours",1874-08-12,Orgeval,Yvelines,FRA,France,NaN,NaN,1932-11-18
17,18,Jean-Philippe Gatien,1968-10-16,Alès,Gard,FRA,France,178.0,73.0,NaN
35,36,Étienne Thobois,1967-09-20,Amiens,Somme,FRA,France,186.0,78.0,NaN
40,41,Julie Bradbury,1967-02-12,Oxford,England,GBR,Great Britain,175.0,64.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145395,149118,Abbey Murphy,2002-04-14,Evergreen Park,Illinois,USA,United States,NaN,NaN,NaN
145398,149121,Grace Zumwinkle,1999-04-23,Excelsior,Minnesota,USA,United States,NaN,NaN,NaN
145405,149128,Brian Cooper,1993-11-01,Anchorage,Alaska,USA,United States,NaN,NaN,NaN
145418,149141,Nick Perbix,1998-06-15,Elk River,Minnesota,USA,United States,NaN,NaN,NaN
145427,149150,Jared Shumate,1999-03-06,Atlanta,Georgia,USA,United States,NaN,NaN,NaN

##### Find atheletes whose name contains exactly two vowels

In [ ]:
two_vowels = bios[bios['name'].str.contains(r"[aeiouAEIOU]{2}", na= False)]
two_vowels

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145485,149212,Radek Houser,1996-07-02,Třebíč,Vysočina,CZE,Czechia,NaN,NaN,NaN
145488,149215,Shakeel John,2001-07-30,Mount Hope,Tunapuna-Piarco,TTO,Trinidad and Tobago,NaN,NaN,NaN
145489,149216,Ye Jielong,2000-03-02,NaN,NaN,NaN,People's Republic of China,NaN,NaN,NaN
145494,149221,George Wright,1890-07-21,Toronto,Ontario,CAN,Canada,183.0,NaN,1973-01-28
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18

##### Find athletes born in year after 2000

In [ ]:
born_19xx = bios[bios['born_date'].str.contains(r"^20", na=False)]
born_19xx

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
126497,128859,Fatima Hirech,2000-08-22,NaN,NaN,NaN,Algeria,170.0,80.0,NaN
126509,128872,Samantha Roberts,2000-04-21,Memphis,Tennessee,USA,Antigua and Barbuda,172.0,64.0,NaN
126564,128931,Gayane Chiloyan,2000-09-27,Yerevan,Yerevan,ARM,Armenia,164.0,54.0,NaN
126620,128993,Ellie Carpenter,2000-04-28,Cowra,New South Wales,AUS,Australia,165.0,59.0,NaN
126676,129054,Aislin Jones,2000-02-08,Shepparton,Victoria,AUS,Australia,157.0,51.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145483,149210,Feng He,2004-03-31,NaN,NaN,NaN,People's Republic of China,NaN,NaN,NaN
145484,149211,Gao Hongbo,2000-10-20,NaN,NaN,NaN,People's Republic of China,NaN,NaN,NaN
145488,149215,Shakeel John,2001-07-30,Mount Hope,Tunapuna-Piarco,TTO,Trinidad and Tobago,NaN,NaN,NaN
145489,149216,Ye Jielong,2000-03-02,NaN,NaN,NaN,People's Republic of China,NaN,NaN,NaN
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN

##### Find athletes whose city contains exactly 5 letters

In [ ]:
city_5letters = bios[bios['born_city'].str.contains(r"^.{5}$", na=False)]
city_5letters

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
8,9,Marcel Cousin,1896-08-04,Nîmes,Gard,FRA,France,NaN,NaN,1986-08-01
18,19,Maurice Germot,1882-11-15,Vichy,Allier,FRA,France,NaN,NaN,1958-08-06
50,51,Alice Greene,1879-10-15,Upton,England,GBR,Great Britain,NaN,NaN,1956-10-26
75,76,Roper Barrett,1873-11-24,Upton,England,GBR,Great Britain,NaN,NaN,1943-07-27
81,82,Andrew Castle,1963-11-15,Epsom,England,GBR,Great Britain,190.0,74.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145421,149144,Nathan Smith,1998-10-19,Tampa,Florida,USA,United States,NaN,NaN,NaN
145448,149172,Aleksandra Glazkova,2006-03-15,Miass,Chelyabinsk,RUS,ROC,NaN,NaN,NaN
145464,149191,Joonas Nättinen,1991-01-03,Jämsä,Keski-Suomi,FIN,Finland,189.0,90.0,NaN
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18

### To pass a list as .contains, we use .isin() method

In [ ]:
bios[bios['born_country'].isin(['IND', 'RUS'])]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
80,81,George Caridia,1869-02-20,Kolkata (Calcutta),West Bengal,IND,Great Britain,NaN,NaN,1937-04-21
101,102,Algernon Kingscote,1888-02-03,Bengaluru (Bangalore),Karnataka,IND,Great Britain,NaN,NaN,1964-12-21
158,159,Robert Spies,1891-02-17,Moskva (Moscow),Moskva,RUS,Germany,NaN,NaN,1982-10-22
270,271,Nora Polley,1894-07-29,Budaun,Uttar Pradesh,IND,India,NaN,NaN,1988-01-01
273,274,Zeeshan Ali,1970-01-01,Kolkata (Calcutta),West Bengal,IND,India,180.0,64.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145487,149214,Yekaterina Kosova,1996-04-25,Moskva (Moscow),Moskva,RUS,ROC,NaN,NaN,NaN
145493,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN

##### To find athletes born in PUNE

In [ ]:
bios[bios['born_city'].str.contains("Pune", na=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
19002,19135,Eliza Nelson,1956-09-27,Pune (Poona),Maharashtra,IND,India,160.0,NaN,NaN
22407,22576,Brian Hamilton,1937-11-13,Pune (Poona),Maharashtra,IND,Ireland,175.0,65.0,NaN
41939,42262,Jocelyn Barlow,1901-08-26,Pune (Poona),Maharashtra,IND,Great Britain,NaN,NaN,1975-01-31
68383,68900,Derek Boosey,1942-07-15,Pune (Poona),Maharashtra,IND,Great Britain,183.0,75.0,NaN
104819,105845,Nikhil Kanetkar,1979-05-13,Pune (Poona),Maharashtra,IND,India,173.0,63.0,NaN
118302,119992,Frank Brewin,1909-10-21,Pune (Poona),Maharashtra,IND,India,NaN,NaN,1976-04-21
131622,134436,Anirban Lahiri,1987-06-29,Pune (Poona),Maharashtra,IND,India,175.0,NaN,NaN

To find athletes born in Maharashtra

In [ ]:
bios[bios['born_region'].str.contains("Maharashtra", na=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
279,280,Ali Athar Fyzee,1883-08-28,Mumbai,Maharashtra,IND,India,NaN,NaN,1963-11-03
285,286,Kamlesh Mehta,1960-05-01,Mumbai,Maharashtra,IND,India,NaN,NaN,NaN
12923,12994,Frank Weldon,1913-08-02,Mumbai,Maharashtra,IND,Great Britain,175.0,66.0,1993-09-21
14593,14691,Bapoo Malcolm,1912-12-12,Mumbai,Maharashtra,IND,India,NaN,NaN,1982-01-19
18611,18738,John Conroy,1928-11-27,Nagpur,Maharashtra,IND,Great Britain,NaN,NaN,1985-11-09
18701,18829,Richard Norris,1931-12-10,Mumbai,Maharashtra,IND,Great Britain,NaN,NaN,2012-08-25
18728,18856,Frederick Scott,1932-11-29,Mumbai,Maharashtra,IND,Great Britain,NaN,NaN,2017-01-01
19002,19135,Eliza Nelson,1956-09-27,Pune (Poona),Maharashtra,IND,India,160.0,NaN,NaN
19012,19145,Richard Allen,1902-06-04,Nagpur,Maharashtra,IND,India,172.0,NaN,1969-01-01
19018,19151,Ashish Kumar Ballal,1970-10-08,Mumbai,Maharashtra,IND,India,NaN,NaN,NaN
19039,19173,Lionel Emmett,1913-01-08,Achalpur,Maharashtra,IND,India,NaN,NaN,1996-08-09
19087,19221,Baboo Nimal,1908-03-15,Khadki,Maharashtra,IND,India,NaN,NaN,1998-02-21
19096,19230,Dhanraj Pillay,1968-07-16,Kirkee,Maharashtra,IND,India,170.0,68.0,NaN
22407,22576,Brian Hamilton,1937-11-13,Pune (Poona),Maharashtra,IND,Ireland,175.0,65.0,NaN
23226,23402,Rolf Edling,1943-11-30,Mumbai,Maharashtra,IND,Sweden,196.0,91.0,NaN
33237,33489,Cawas Billimoria,1962-10-25,Mumbai,Maharashtra,IND,India,NaN,NaN,NaN
41939,42262,Jocelyn Barlow,1901-08-26,Pune (Poona),Maharashtra,IND,Great Britain,NaN,NaN,1975-01-31
47050,47400,Peter Squires,1936-05-28,Mumbai,Maharashtra,IND,Great Britain,168.0,63.0,2011-09-16
47924,48276,Shrichand Bajaj,1933-10-01,Mumbai,Maharashtra,IND,India,NaN,NaN,2005-07-20
47930,48282,Isaac Mansoor,1929-05-30,Mumbai,Maharashtra,IND,India,NaN,NaN,2006-01-01
53847,54233,David Sopher,1929-02-01,Mumbai,Maharashtra,IND,India,NaN,NaN,2019-02-14
56044,56442,Rory Barrett,1945-12-31,Mumbai,Maharashtra,IND,New Zealand,185.0,110.0,NaN
58269,58683,Ganpat Andhalkar,1935-04-15,Punwat,Maharashtra,IND,India,183.0,97.0,2018-09-16
58279,58693,Harishchandra Birajdar,1950-06-05,Nilangana,Maharashtra,IND,India,192.0,100.0,2011-09-14
58290,58704,Maruti Mane,1938-08-10,Kavthepiran,Maharashtra,IND,India,175.0,97.0,2010-07-27
58308,58722,Dinkkarao Shinde,1900-01-01,Kolhapur,Maharashtra,IND,India,NaN,NaN,NaN
62023,62479,Harry Jefferson,1849-03-09,Mumbai,Maharashtra,IND,Great Britain,NaN,NaN,1918-06-23
63392,63868,Farokh Tarapore,1960-08-03,Satpati,Maharashtra,IND,India,179.0,60.0,NaN
68383,68900,Derek Boosey,1942-07-15,Pune (Poona),Maharashtra,IND,Great Britain,183.0,75.0,NaN
68517,69034,Launceston Elliot,1874-06-09,Mumbai,Maharashtra,IND,Great Britain,188.0,102.0,1930-08-08
69609,70130,Manisha Malhotra,1976-09-19,Mumbai,Maharashtra,IND,India,NaN,NaN,NaN
70879,71411,Eddie Sequeira,1942-02-06,Mumbai,Maharashtra,IND,India,172.0,54.0,NaN
72084,72630,Shoichiro Takenaka,1912-09-30,Mumbai,Maharashtra,IND,Japan,158.0,46.0,1997-04-04
82089,82742,Aparna Popat,1978-01-18,Mumbai,Maharashtra,IND,India,160.0,65.0,NaN
83644,84307,John Boyagis,1928-01-26,Mumbai,Maharashtra,IND,Great Britain,NaN,NaN,2020-07-22
90937,91661,Robin D'Abreo,1975-03-03,Mumbai,Maharashtra,IND,Canada,178.0,66.0,NaN
90978,91704,Jude Menezes,1971-08-05,Mumbai,Maharashtra,IND,India,172.0,75.0,NaN
92337,93077,Anjali Vedpathak-Bhagwat,1969-12-05,Mumbai,Maharashtra,IND,India,165.0,53.0,NaN
101677,102603,Pat Sullivan,1909-08-30,Lonavla,Maharashtra,IND,India,173.0,NaN,1981-01-01
103745,104738,Deepali Deshpande,1969-08-03,Mumbai,Maharashtra,IND,India,159.0,54.0,NaN
104819,105845,Nikhil Kanetkar,1979-05-13,Pune (Poona),Maharashtra,IND,India,173.0,63.0,NaN
107863,109001,Vikram Pillay,1981-11-27,Kirkee,Maharashtra,IND,India,162.0,72.0,NaN
107864,109002,Viren Rasquinha,1980-09-13,Mumbai,Maharashtra,IND,India,170.0,65.0,NaN
114280,115587,Virdhawal Khade,1991-08-29,Kolhapur,Maharashtra,IND,India,191.0,83.0,NaN
118302,119992,Frank Brewin,1909-10-21,Pune (Poona),Maharashtra,IND,India,NaN,NaN,1976-04-21
119207,121001,Rahi Sarnobat,1990-10-30,Kolhapur,Maharashtra,IND,India,158.0,66.0,NaN
119636,121462,Mayookha Johny,1988-04-09,Mumbai,Maharashtra,IND,India,174.0,58.0,NaN
122966,125116,Jwala Gutta,1983-09-07,Wardha,Maharashtra,IND,India,178.0,85.0,NaN
128041,130545,Lalita Babar,1989-06-02,Satara District,Maharashtra,IND,India,166.0,50.0,NaN
128066,130572,Ayonika Paul,1992-09-23,Mumbai,Maharashtra,IND,India,174.0,74.0,NaN
128068,130574,Prarthana Thombare,1994-06-18,Barshi,Maharashtra,IND,India,165.0,58.0,NaN
130375,133059,Keegan Pereira,1991-09-08,Mumbai,Maharashtra,IND,Canada,166.0,59.0,NaN
131622,134436,Anirban Lahiri,1987-06-29,Pune (Poona),Maharashtra,IND,India,175.0,NaN,NaN
131627,134441,Devindar Walmiki,1992-05-28,Mumbai,Maharashtra,IND,India,178.0,69.0,NaN
131632,134448,Dattu Baban Bhokanal,1991-04-05,Nashik,Maharashtra,IND,India,189.0,81.0,NaN
134610,137691,Anice Das,1985-12-31,Mumbai,Maharashtra,IND,Netherlands,170.0,65.0,NaN

In [ ]:
two_vowels = bios[bios['born_country'].str.contains(r"USA", na= False) & bios['name'].str.startswith(r"Keith", na= False)]
two_vowels
# gives names starting with Keith and born in USA

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
50929,51288,Keith Carter,1924-08-30,Akron,Ohio,USA,United States,NaN,NaN,2013-05-03
51185,51544,Keith Russell,1948-01-15,Mesa,Arizona,USA,United States,188.0,73.0,NaN
52913,53288,Keith Erickson,1944-04-19,San Francisco,California,USA,United States,196.0,86.0,NaN
62678,63144,Keith Notary,1960-01-22,Merritt Island,Florida,USA,United States,170.0,66.0,NaN
77550,78141,Keith Brantly,1962-05-23,Scott Air Force Base,Illinois,USA,United States,180.0,64.0,NaN
84097,84766,Keith Christiansen,1944-07-14,International Falls,Minnesota,USA,United States,165.0,69.0,2018-11-05
94646,95413,Keith Meyer,1938-06-20,Geneva,Illinois,USA,United States,NaN,NaN,2010-07-25
97499,98286,Keith Tkachuk,1972-03-28,Melrose,Massachusetts,USA,United States,188.0,102.0,NaN
98068,98860,Keith Wegeman,1929-08-28,Denver,Colorado,USA,United States,NaN,NaN,1974-08-22
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN