# Introduction to Dataframes

### importing pandas

In [1]:
import pandas as pd

#### **Dataframe** is the main data structure of Pandas library
#### They are simply tables with wide variety of functions
#### Allows to work with spreadsheets

In [4]:
df = pd.DataFrame([[1,2,3],[4,5,2],[9,8,3]], columns = ["A","B","C"])  # a simple dataframe with 2D array
df.head()

   A  B  C
0  1  2  3
1  4  5  2
2  9  8  3

##### To acces only the first row

In [5]:
df.head(1)

   A  B  C
0  1  2  3

##### To acces bottom two rows

In [6]:
df.tail(2)

   A  B  C
1  4  5  2
2  9  8  3

##### By default, index are numerical. But we can specify the index while crating the dataframe

In [7]:
df = pd.DataFrame([[1,2,3],[4,5,2],[9,8,3]], columns = ["X","Y","Z"], index = ["p","q","r"])

In [8]:
df

   X  Y  Z
p  1  2  3
q  4  5  2
r  9  8  3

In [11]:
df.columns #displays all the columns

Index(['X', 'Y', 'Z'], dtype='object')

In [13]:
df.index    #displays all the indexes

Index(['p', 'q', 'r'], dtype='object')

In [14]:
df.info()     #to get all information about the dataframe

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, p to r
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X       3 non-null      int64
 1   Y       3 non-null      int64
 2   Z       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0+ bytes

In [15]:
df.describe()     #gives meaningful (statistical information) information about the data

              X    Y         Z
count  3.000000  3.0  3.000000
mean   4.666667  5.0  2.666667
std    4.041452  3.0  0.577350
min    1.000000  2.0  2.000000
25%    2.500000  3.5  2.500000
50%    4.000000  5.0  3.000000
75%    6.500000  6.5  3.000000
max    9.000000  8.0  3.000000

In [18]:
df.nunique()   #gives number of the unique values in each column

X    3
Y    3
Z    2
dtype: int64

In [19]:
df["X"].unique()    #gives unique values from a specific column

array([1, 4, 9])

In [20]:
df.shape      #gives the number of rows and column

(3, 3)

In [22]:
df.size    #gives the size of the dataframe

9